import os
import sys
import ipinfo
import argparse


def parser_section():
    parser = argparse.ArgumentParser(
        description="Volatility 3 Network Scan Parser & Geolocator. By Riccardo Deidda, Version: 15-01-2026")
    parser.add_argument("-f", "--file",
                        help="Path to the netscan.txt file")

    parser.add_argument("-t", "--token",
                        help="ipinfo.io API Access Token")
    args = parser.parse_args()
    netscan_checker(args.file)
    return args


def print_ip_details(ip_set, label, access_token):
    handler = ipinfo.getHandler(access_token)
    print(f"\n---- {label} DETAILS ----")
    if not ip_set:
        print("No unique external IPs found.")
        return
    for ip in ip_set:
        try:
            details = handler.getDetails(ip)
            city = getattr(details, "city", "Unknown")
            country = getattr(details, "country_name", "Unknown")
            org = getattr(details, "org", "N/A")
            print(f"IP: {ip:<25} | City: {city:<25} | Country: {country:<25} | Org: {org:<25}")
        except Exception:
            print(f"IP: {ip:<25} | Could not retrieve data (Private/Invalid)")


def netscan_checker(netscan_path):
    if not os.path.exists(netscan_path):
        print(f"Error: File '{netscan_path}' not found.")
        sys.exit(1)
    with open(netscan_path, "r", encoding="utf-16") as f:
        lines = [f.readline().strip() for _ in range(3)]
        if "Volatility 3 Framework" not in lines[0]:
            print("Error: This file was not generated by Volatility 3.")
            sys.exit(1)
        expected_headers = ["Offset", "Proto", "LocalAddr", "ForeignAddr"]
        if not all(h in lines[2] for h in expected_headers):
            print("Error: Not a valid netscan.txt file (Columns mismatch).")
            sys.exit(1)
    print(f"[*] File validation successful: {os.path.basename(netscan_path)}")


def netscan_parser(netscan_path):
    exclusion_char = ['*', '::', '::1', '0.0.0.0', '127.0.0.1']

    local_addr = set()
    foreign_addr = set()
    with open(netscan_path, "r", encoding="utf-16") as f:
        for line in f:
            parts = line.strip().split()
            if not parts or parts[0] in ["Volatility", "Offset", "Proto"]:
                continue
            try:
                local_ip = parts[2]
                foreign_ip = parts[4]
                if local_ip not in exclusion_char: local_addr.add(local_ip)
                if foreign_ip not in exclusion_char: foreign_addr.add(foreign_ip)
            except IndexError:
                continue
    return local_addr, foreign_addr


if __name__ == "__main__":
    args = parser_section()
    local_ips, foreign_ips = netscan_parser(args.file)
    local_ips = sorted(local_ips)
    foreign_ips = sorted(foreign_ips)
    print_ip_details(local_ips, "LOCAL ADDRESSES", args.token)
    print_ip_details(foreign_ips, "FOREIGN ADDRESSES", args.token)
